
CREATE TABLE "public"."fileformats"("id" text NOT NULL, "comment" text NOT NULL, PRIMARY KEY ("id") ); COMMENT ON TABLE "public"."fileformats" IS E'Databrary MIME Types';
INSERT INTO "public"."fileformats" VALUES ('csv', 'Comma-separated values');
INSERT INTO "public"."fileformats" VALUES ('rtf', 'Rich Text format');
INSERT INTO "public"."fileformats" VALUES ('png', 'Portable network graphics');
INSERT INTO "public"."fileformats" VALUES ('pdf', 'Portable document');
INSERT INTO "public"."fileformats" VALUES ('doc', 'Microsoft Word document');
INSERT INTO "public"."fileformats" VALUES ('odf', 'OpenDocument text');
INSERT INTO "public"."fileformats" VALUES ('docx', 'Microsoft Word (Office Open XML) document');
INSERT INTO "public"."fileformats" VALUES ('xls', 'Microsoft Excel spreadsheet');
INSERT INTO "public"."fileformats" VALUES ('ods', 'OpenDocument spreadsheet');
INSERT INTO "public"."fileformats" VALUES ('xlsx', 'Microsoft Excel (Office Open XML) workbook');
INSERT INTO "public"."fileformats" VALUES ('ppt', 'Microsoft PowerPoint presentation');
INSERT INTO "public"."fileformats" VALUES ('odp', 'OpenDocument presentation');
INSERT INTO "public"."fileformats" VALUES ('pptx', 'Microsoft PowerPoint (Office Open XML) presentation');
INSERT INTO "public"."fileformats" VALUES ('opf', 'Datavyu');
INSERT INTO "public"."fileformats" VALUES ('sav', 'SPSS System File');
INSERT INTO "public"."fileformats" VALUES ('its', 'LENA Interpreted Time Segments');
INSERT INTO "public"."fileformats" VALUES ('txt', 'Plain text');
INSERT INTO "public"."fileformats" VALUES ('cha', 'Codes for the Human Analysis of Transcripts');
INSERT INTO "public"."fileformats" VALUES ('chat', 'Codes for the Human Analysis of Transcripts');
INSERT INTO "public"."fileformats" VALUES ('eaf', 'ELAN - Linguistic Annotator');
INSERT INTO "public"."fileformats" VALUES ('pfsx', 'ELAN - Linguistic Annotator');
INSERT INTO "public"."fileformats" VALUES ('etf', 'ELAN - Linguistic Annotator');
INSERT INTO "public"."fileformats" VALUES ('jpg', 'JPEG image');
INSERT INTO "public"."fileformats" VALUES ('jpeg', 'JPEG image');
INSERT INTO "public"."fileformats" VALUES ('webm', 'WebM video');
INSERT INTO "public"."fileformats" VALUES ('mpg', 'MPEG program stream (MPEG-1/MPEG-2 video)');
INSERT INTO "public"."fileformats" VALUES ('mpeg', 'MPEG program stream (MPEG-1/MPEG-2 video)');
INSERT INTO "public"."fileformats" VALUES ('mov', 'QuickTime video');
INSERT INTO "public"."fileformats" VALUES ('mts', 'MPEG transport stream');
INSERT INTO "public"."fileformats" VALUES ('m2ts', 'MPEG transport stream');
INSERT INTO "public"."fileformats" VALUES ('avi', 'Audio Video Interleave');
INSERT INTO "public"."fileformats" VALUES ('wmv', 'Windows Media video');
INSERT INTO "public"."fileformats" VALUES ('dv', 'Digital Interface Format video');
INSERT INTO "public"."fileformats" VALUES ('dif', 'Digital Interface Format video');
INSERT INTO "public"."fileformats" VALUES ('mp4', 'MPEG-4 video');
INSERT INTO "public"."fileformats" VALUES ('wav', 'Waveform audio');
INSERT INTO "public"."fileformats" VALUES ('aac', 'Advanced Audio Coding');
INSERT INTO "public"."fileformats" VALUES ('wma', 'Windows Media audio');
INSERT INTO "public"."fileformats" VALUES ('mp3', 'MPEG-1 or MPEG-2 audio layer III');