mutation (
  $name: String!, 
  $assetType: asset_types_enum!
  $parentId: Int,
) {
  insert_assets(
    objects: {
      parentId: $parentId,
      name: $name,
      assetType: $assetType,
      privacyType: private
    }
  ) {
    returning {
      id
    }
  }
}