query getAvatarAsset (
    $dbId: Int!
) {
  users(where: {id: {_eq: $dbId}}) {
    id
    useGravatar
    avatar {
      id
      files(where: {fileobject: {id: {_is_null: false}}}) {
        name
        uploadedDatetime
        fileobject {
          location
          size
          md5
          sha1
          sha256
        }
      }
    }
  }
}