query getProjectPage {
  assets(
    where: {
      assetType: {
        _eq: project
      }, 
      id: {
        _eq: 10
      }
    }
  ) {
    id
    privacyType
    name
    datetimeCreated
    assetType
  }
}