  query getUserByEmail($email: String!) {
    users(
      where: {
        emailPrimary: {
          _eq: $email
        }
      }
    ) {
      id
      authServerId
      emailPrimary
      displayFullName
      useGravatar
      image
      gravatar
    }
  }