  query getUserByEmail($email: String!) {
    users(
      where: {
        emailPrimary: {
          _eq: $email
        }
      }
    ) {
      id
      authServerId
      emailPrimary
      displayFullName
      useGravatar
      image
      gravatar
      urls
      emails
      additionalName
      familyName
      givenName
      bio
      orcid
    }
  }