query getUserByAuthId($authServerId: String!) {
  users(
    where: {
      authServerId: {
        _eq: $authServerId
      }
    }
  ) {
    id
    emailPrimary
    displayFullName
    useGravatar
    image
    gravatar
    urls
    emails
    additionalName
    familyName
    givenName
    bio
    orcid
  }
}