query getUserByEmail($emailPrimary: String!) {
  users(
    where: {
      emailPrimary: {
        _eq: $emailPrimary
      }
    }
  ) {
    id
    emailPrimary
    displayFullName
    useGravatar
    image
    gravatar
    urls
    emails
    additionalName
    familyName
    givenName
    bio
    orcid
  }
}