mutation insertAsset (
    $createdById: Int!
    $name: String!
    $assetType: asset_types_enum!
    $privacyType: privacy_types_enum!
    $parentId: Int
) {
  insert_assets(
      objects: {
          assetType: $assetType, 
          createdById: $createdById, 
          name: $name, 
          privacyType: $privacyType,
          parentId: $parentId
    }
    ) {
        returning {
            id
            name
            assetType
            privacyType
            createdById
            datetimeCreated
            permissionsetId
            parentId
        }
    }
}