# TODO(Reda): change fileFormatID to fileformats_enum to restrict the format upload
mutation ( 
  $name: String!,
  $uploadedById: Int!,
  $assetId: Int!,
  $fileFormatId: String!
) {
  insert_files(
    objects: { 
      name: $name,
      uploadedById: $uploadedById,
      assetId: $assetId,
      fileFormatId: $fileFormatId
    }
  ) {
    returning {
      id
    }
  }
}