mutation insertAvatarAsset (
    $userId: Int
    $name: String
) {
  insert_assets(
      objects: {
          asset_type: avatar, 
          created_by_id: $userId, 
          name: $name, 
          privacy_type: public
          }
    ) {
        returning {
            id
        }
    }
}