mutation registerUser(
    $id: Int,
    $authServerId: String!,
    $emailPrimary: String!,
    $givenName: String!,
    $familyName: String!,
    $additionalName: String,
    $displayFullName: String!,
    $emails: jsonb!,
    $urls: jsonb,
    $gravatar: jsonb!,
    $image: jsonb,
    $bio: String
) {
    insert_users(objects: {
      id: $id,
      authServerId: $authServerId,
      emailPrimary: $emailPrimary,
      givenName: $givenName,
      familyName: $familyName,
      additionalName: $additionalName,
      displayFullName: $displayFullName,
      emails: $emails,
      urls: $urls,
      gravatar: $gravatar
      image: $image,
      bio: $bio
    }) {
      returning {
        id
        emailPrimary
        displayFullName
        useGravatar
        image
        gravatar
        urls
        emails
        additionalName
        familyName
        givenName
        bio
        orcid
      }
    }
  }