mutation registerUser(
    $authServerId: String!,
    $emailPrimary: String!,
    $givenName: String,
    $familyName: String,
    $additionalName: String,
    $displayFullName: String,
    $emails: jsonb,
    $urls: jsonb,
    $gravatar: jsonb ) 
  {
    insert_users(objects: {
      authServerId: $authServerId,
      emailPrimary: $emailPrimary,
      givenName: $givenName,
      familyName: $familyName,
      additionalName: $additionalName,
      displayFullName: $displayFullName,
      emails: $emails,
      urls: $urls,
      gravatar: $gravatar
    }) {
      returning {
        id
        authServerId
        emailPrimary
        displayFullName
        useGravatar
        image
        gravatar
        urls
        emails
        additionalName
        familyName
        givenName
        bio
        orcid
      }
    }
  }