mutation updateFile ($fileId: Int, $fileobjectId: Int, $uploadedDatetime: timestamp) {
  update_files(
    where: {id: {_eq: $fileId}},
    _set: {
      fileobjectId: $fileobjectId,
      uploadedDatetime: $uploadedDatetime
    }
  ) {
    returning {
      id,
      uploadedById
    }
  }
}