mutation UpdateAssetName(
    $assetId: Int!, 
    $name: String!
) {
  update_assets(
    where: { 
        id: { _eq: $assetId }
    }
    _set: { name: $name }
  ) {
    returning {
      name
    }
  }
}
